site_name: Cybercraft 5e
site_url: https://bruhfessorx.github.io/cybercraft5e/
repo_url: https://github.com/BruhfessorX/cybercraft5e
repo_name: BruhfessorX/cybercraft5e
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple   # name, not hex
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css


nav:
  - Home: index.md
  - Player Options:
      - Races:
          - Races Overview: player-options/races.md
          - Humans: player-options/races/humans.md
          - Vampyrus: player-options/races/vampyrus.md
          - Umbraliths: player-options/races/umbraliths.md
          - Anomalie: player-options/races/anomalie.md
          - Synthetics: player-options/races/synthetics.md
          - Lycans: player-options/races/lycan.md
      - Classes:
          - Classes Overview: player-options/classes.md
          - Fleshshaper: player-options/classes/fleshshaper.md
          - Ghostlink: player-options/classes/ghostlink.md
          - Scriptweaver: player-options/classes/scriptweaver.md
          - Veilbreaker: player-options/classes/veilbreaker.md
          - Voidrunner: player-options/classes/voidrunner.md
          - Warjack: player-options/classes/warjack.md
      - Backgrounds: player-options/backgrounds.md
      - Feats: player-options/feats.md
      - Gear & Items:
          - Overview: gear-items/overview.md
          - Weapons: gear-items/weapons.md
          - Armor: gear-items/armor.md
          - Cybernetics: gear-items/cybernetics.md
          - Devices & Gear: gear-items/devices-and-gear.md
      - Spells:
          - Overview: player-options/spells/overview.md
          - Technomancy: player-options/spells/technomancy.md
          - Voidcraft: player-options/spells/voidcraft.md
          - Urban Utility: player-options/spells/urban-utility.md

  - Rules:
      - Core Rules: rules/core-rules.md
      - Combat: rules/combat.md
      - Skill Checks: rules/skills-checks.md
      - Economy: rules/economy.md
      - Sanity & Corruption: rules/sanity-corruption.md
  - Game Master:
      - Setting Overview: game-master/setting-overview.md
      - Factions: game-master/factions.md
      - City Zones: game-master/city-zones.md
      - Anomalies: game-master/anomalies.md
      - Bestiary: game-master/bestiary.md
      - Running the Game: game-master/running.md
  - Resources:
      - Quick Reference: resources/quick-reference.md
      - Character Sheet: resources/character-sheet.md
      - Legal: resources/legal.md
  - Tales from the Veil:
      - Overview: tales-from-the-veil/overview
      - Journal Entries: tales-from-the-veil/journal-entries.md
      - Whispers of the Street: tales-from-the-veil/whispers-street.md
      - Fragments from the Net: tales-from-the-veil/fragments-net.md
      - Corporate Memos: tales-from-the-veil/corporate-memos.md
      - Cult Scriptures: tales-from-the-veil/cult-scriptures.md

      
nav_descriptions:
  player-options/races/humans.md: "Adaptable, resilient, and endlessly diverse."
  player-options/races/vampyrus.md: "Immortal predators ruling in secrecy."
  player-options/races/umbraliths.md: "Void-born entities infused with darkness."
  player-options/races/anomalie.md: "Living anomalies that defy natural law."
  player-options/races/synthetics.md: "Intelligent machines shaped by design or rebellion."
  player-options/races/lycan.md: "Genetic callbacks to humanities feral nature associated to the veil."
  player-options/classes/fleshshaper.md: "Masters of bio-modification and adaptive fleshcraft."
  player-options/classes/ghostlink.md: "Digital infiltrators who merge mind and machine."
  player-options/classes/scriptweaver.md: "Hackers of reality, weaving code and arcane logic."
  player-options/classes/veilbreaker.md: "Hunters of the hidden, tearing through lies and illusions."
  player-options/classes/voidrunner.md: "Navigators of the void, thriving in hostile environments."
  player-options/classes/warjack.md: "Heavy cybernetic warriors built for frontline combat."




markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BruhfessorX/cybercraft5e
      name: GitHub
    - icon: material/email
      link: captainhornigold77@gmail.com
      name: Email
  copyright: >
    © 2025 Cybercraft 5e. All content is licensed under the
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0 License</a>
    unless otherwise noted.

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: false